baseURL = "https://salazr.dev"
languageCode = "en-us"
title = "BERNARDO SALAZAR"

[params]
  description = "A house with many doors and windows."

[author]
    name = "Bernardo Salazar"
    homepage = "http://salazr.dev"

[menus]
  main = [
    # uncomment when I have posts
    # {name = "Posts", url = "/posts", weight = 1},
    # {name = "About", url = "/about", weight = 2},
  ]
