baseURL = "https://salazr.dev"
languageCode = "en-us"
title = "salazr.dev"

[params]
  description = "A house with many doors and windows."
  name = "BERNARDO SALAZAR"

[author]
    name = "Bernardo Salazar"
    homepage = "http://salazr.dev"
[menus]
  main = [
    # {name = "Posts", url = "/posts", weight = 1},
    # {name = "Experience", url = "/xp", weight = 2},
    # {name = "About me", url = "/about", weight = 3},
  ]
